$kind: http-request
name: update_roles
url: "{{hrms.com}}/admin/update_Roles/EMPLOYE"
method: PUT
body:
  type: json
  content: "{\r

    \    \"name\": \"EMPLOYEE\",\r

    \    \"description\": \"\"\r

    }"
order: 3000
